name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: 12.13
      - name: Install dependencies
        run: yarn
      - name: Build Container
        run: docker-compose build
  unit:
    needs: build
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Test
        run: docker-compose run main yarn test
  e2e:
    needs: build
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: docker-compose -f docker-compose.e2e.yml up --abort-on-container-exit --exit-code-from main
