name: CI
on: [push]
jobs:
  build:
    name: Build
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Container
        run: docker-compose build
      - run: docker login docker.pkg.github.com -u ${{ github.actor }} -p "${{ secrets.GITHUB_TOKEN }}"
      - run: docker-compose push
  unit:
    needs: build
    continue-on-error: false
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login docker.pkg.github.com -u ${{ github.actor }} -p "${{ secrets.GITHUB_TOKEN }}"
      - run: docker-compose pull
      - name: Unit Test
        run: docker-compose run main yarn test
  e2e:
    needs: build
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker login docker.pkg.github.com -u ${{ github.actor }} -p "${{ secrets.GITHUB_TOKEN }}"
    - run: docker-compose pull
    - name: Run E2E Test
      run: docker-compose -f docker-compose.e2e.yml up --abort-on-container-exit --exit-code-from main
